"""delete oncascacade from recipe.category_id

Revision ID: c00c03ae5fb0
Revises: c089a8d344f9
Create Date: 2023-05-03 10:56:53.011823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00c03ae5fb0'
down_revision = 'c089a8d344f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint('recipes_category_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('recipes_category_id_fkey', 'categories', ['category_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
