"""empty message

Revision ID: e1cd923c4094
Revises: 7122c49e86d5
Create Date: 2023-05-04 10:56:55.988498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1cd923c4094'
down_revision = '7122c49e86d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=False))
        batch_op.drop_column('rating_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('recipe_id')

    # ### end Alembic commands ###
